const translateStateName = {
  "Anhui": "安徽",
  "Fujian": "福建",
  "Gansu": "甘肃",
  "Guangxi Zhuang": "广西",
  "Beijing": "北京",
  "Chongqing": "重庆",
  "Guangdong": "广东",
  "Guizhou": "贵州",
  "Hainan": "海南",
  "Hebei": "河北",
  "Henan": "河南",
  "Hong Kong": "香港",
  "Heilongjiang": "黑龙江",
  "Hunan": "湖南",
  "Hubei": "湖北",
  "Jilin": "吉林",
  "Jiangsu": "江苏",
  "Jiangxi": "江西",
  "Liaoning": "辽宁",
  "Macau": "澳门",
  "Nei Mongol": "内蒙古",
  "Ningxia Hui": "宁夏",
  "Quinghai": "青海",
  "Shaanxi": "陕西",
  "Sichuan": "四川",
  "Shandong": "山东",
  "Shanghai": "上海",
  "Shanxi": "山西",
  "Tianjin": "天津",
  "Taiwan": "台湾",
  "Xinjiang Uygur": "新疆",
  "Xizang (Tibet)": "西藏",
  "Yunnan": "云南",
  "Zhejiang": "浙江",
};

export default translateStateName;
